name: Start Render

on:
  schedule:
    - cron: "57 20 * * *"
  workflow_dispatch:

jobs:
  start-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Resume Render
        run: |
          curl -X POST \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/resume \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
