name: Iniciar Render Bot

on:
  schedule:
    - cron: "0 21 * *"
  workflow_dispatch:

jobs:
  iniciar-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Resumir Render
      run: | 
        curl -X POST \ 
        https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/resume \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
