name: Stop Render

on:
  schedule:
    - cron: "57 2 * * *"
  workflow_dispatch:

jobs:
  stop-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Suspend Render
        run: |
          curl -X POST \
          https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/suspend \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
